# Generated by Django 5.1.5 on 2025-01-30 23:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hub', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cliente',
            name='imagem',
            field=models.ImageField(blank=True, default='0', max_length=500, upload_to='imagens/'),
        ),
    ]
